#배포 환경 
#추후 작성
#spring:
#  datasource:
#    url: jdbc:mariadb://${prodDbIp}:3306/code_care_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#    username: ${prodDbId:code_care}
#    password: ${prodDbPw:}
#  jpa:
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        use_sql_comments: false
#    hibernate:
#      ddl-auto: none
#logging:
#  level:
#    root: info
#    site.codecare: debug
#    org.hibernate.type.descriptor.sql: info
#custom:
#  site:
#    baseUrl: "https://service-domain"