spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
    site.codecare: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: Code-Care
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: