server:
  port: 80
spring:
  datasource:
# TODO : DB 서버 생성 후 수정 해야함
    url: jdbc:mariadb://127.0.0.1:3306/code_care_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: code_care
    password: ENC(wveEFiKe50Bs4JNiQ84wJxeyTLKLv8Sk)
  jpa:
    hibernate:
      ddl-auto: update