server:
  port: 80
spring:
  datasource:
# TODO : DB 서버 생성 후 수정 해야함
    url: jdbc:mariadb://db-e5te7.pub-cdb.ntruss.com/code_care_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: code_care
    password: ENC(kwx4ldA3fMn0rruoUDWKa3JDwD/qfHGg)
  jpa:
    hibernate:
      ddl-auto: create
jasypt:
  encryptor:
    bean: jasyptStringEncryptor